version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: eshop-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eshop
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - eshop-network

 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: eshop-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - eshop-network


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eshop-backend
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: eshop
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - eshop-network


  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eshop-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - eshop-network
    depends_on:
      - backend

  frontend-dev:
    build:
      context: ./src
      dockerfile: Dockerfile.dev
    container_name: eshop-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app
      - /app/node_modules
    command: npm run dev -- --host
    networks:
      - eshop-network
    profiles:
      - dev

networks:
  eshop-network:
    driver: bridge
