apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eshop-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - eshop.example.com
    secretName: eshop-tls
  rules:
  - host: eshop.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eshop-frontend-service
            port:
              number: 80