apiVersion: v1
kind: Service
metadata:
  name: eshop-frontend-service
  labels:
    app: eshop-frontend
spec:
  type: LoadBalancer
  selector:
    app: eshop-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  sessionAffinity: ClientIP
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-frontend-nodeport
  labels:
    app: eshop-frontend
spec:
  type: NodePort
  selector:
    app: eshop-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP